version: '3'
services:
  hanbai_app:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
    tty: true
    volumes:
      - ./src:/src
    working_dir: /src
    ports:
      - "3000:3000"
    networks:
       hanbai_network:

  postgre_hanbai:
    container_name: postgre_task
    build: ./docker/postgresql 
    environment:
      TZ: 'Asia/Tokyo'
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgresql/init:/docker-entrypoint-initdb.d
      - ./src:/src
      - hanbai-db-data:/var/lib/postgresql/data
    working_dir: /src
    networks:
       hanbai_network:
          ipv4_address: 172.25.2.89
  db:
    image: mysql:8.0
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./docker/db/data:/var/lib/mysql
    - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
    - 3308:3306
    networks:
     hanbai_network:
      ipv4_address: 172.25.2.90

networks:
  hanbai_network:
      ipam:
        driver: default
        config:
          - subnet: 172.25.2.0/24
volumes:
  hanbai-db-data:
  db-store: